
vector:
  logLevel: "debug"  # checked what debugging would output

  customConfig:
    sources:
      kubernetes:
        type: kubernetes_logs
        self_node_name: mb  # `kubectl get nodes`
      vector:
        address: 0.0.0.0:6000
        type: vector
        version: "2"
    sinks:
      console_stdout:
        type: console
        inputs:
          - kubernetes
          - vector
        encoding:
          codec: text
