# flux-manifests/vector-helm-repo.yaml
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: vector
  namespace: flux-system
spec:
  url: https://helm.vector.dev
  interval: 5m
